version: '2.0'

services:
    web:
        build: nginx
        container_name: ${PROJECT_NAME}_nginx
        volumes:
            - ../:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/fastcgi_yii.conf:/etc/nginx/fastcgi_yii
            - ./nginx/locations.conf:/etc/nginx/locations
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/upstream.conf:/etc/nginx/upstream
        ports:
            - ${WEB_PORT}:80
        environment:
            - HOST='${HOST}'
            - PHP_FPM_PATH='${PROJECT_NAME}_php-fpm:9000'
            - host_path='/var/www/html'
        command: /bin/sh -c "envsubst < /etc/nginx/upstream > /etc/nginx/upstream.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php-fpm
        networks:
            project_net:
                ipv4_address: 172.28.5.8

    php-fpm:
        build:
            context: php-fpm
            args:
                - YOUR_IP_ADDRESS={{YOUR_IP_ADDRESS}}
                - XDG_CACHE_HOME=/var/www/html
        container_name: ${PROJECT_NAME}_php-fpm
        ports:
            - 9000
        environment:
            XDEBUG_CONFIG: "remote_host=${XDEBUG_REMOTE_HOST} remote_enable=1"
            PHP_IDE_CONFIG: "serverName=${PHP_IDE_CONFIG_SERVER_NAME}"
        volumes:
            - ../:/var/www/html
            - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
            - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
        depends_on:
            - postgres
        networks:
            project_net:
                ipv4_address: 172.28.5.7

    pgadmin:
        image: dpage/pgadmin4
        container_name: ${PROJECT_NAME}_pgadmin
        ports:
            - ${PG_PORT}:80
        volumes:
            - ./pg/data:/var/lib/postgresql/data
        environment:
            - PGADMIN_DEFAULT_PASSWORD=0
            - PGADMIN_DEFAULT_EMAIL=dump@null
        networks:
            project_net:
                ipv4_address: 172.28.5.4

    redis:
        container_name: ${PROJECT_NAME}_redis
        image: redis:latest
        networks:
            project_net:
                ipv4_address: 172.28.5.6

    postgres:
        restart: always
        container_name: ${PROJECT_NAME}_postgres
        image: postgres:11.3
        ports:
            - 5432:5432
        volumes:
            - ./pg/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=${PG_PASSWORD}
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_DB=${PG_DATABASE}
        networks:
            project_net:
                ipv4_address: 172.28.5.5

networks:
    project_net:
        ipam:
            config:
                -   subnet: 172.28.0.0/16
                    ip_range: 172.28.5.0/24
                    gateway: 172.28.5.254